### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by denisw** [europeana/spring-batch-mongo#2]
There seems to be no indication of which license this project is licensed under. It would be great of a LICENSE file could be added.

**Comment by ikattey** [comment]
Thanks for bringing this to our attention @denisw.

A [license file](https://github.com/europeana/spring-batch-mongo/blob/master/LICENSE.md) is now added to the project.

In principle, this license retroactively applies to previous versions; however we've also created a new release with this change ([v1.0.6](https://github.com/europeana/spring-batch-mongo/releases/tag/spring-batch-mongo-1.0.6)).

**Comment by denisw** [comment]
Wow, thanks for the quick fix! :+1:
